// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkittmgkpqvpngvbptma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJraXR0bWdrcHF2cG5ndmJwdG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Njc5NjUsImV4cCI6MjA2MjQ0Mzk2NX0.ki749c5SPWcAGtFD2hbqTzyka5H-mSFtTpG0qTOgsmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);